import fs from 'node:fs/promises';
import path from 'node:path';
import type { DeckEntry } from './generated-switcher-template.js';
import { renderNavControlComponent } from './generated-switcher-template.js';

const NAV_CONTROLS_FILENAME = 'custom-nav-controls.vue';
const GENERATED_MARKER = 'Generated by vite-plugin-slidev-manager';

export interface GenerateDevSwitcherOptions {
    deckRoot: string;
    decks: DeckEntry[];
    currentSlug: string;
    bridgeUrl: string;
}

export interface GenerateDevSwitcherResult {
    navControlsPath: string;
}

export async function generateDevSwitcherFiles(
    options: GenerateDevSwitcherOptions,
): Promise<GenerateDevSwitcherResult> {
    const { deckRoot, decks, currentSlug, bridgeUrl } = options;

    const templateOptions = { decks, currentSlug, bridgeUrl };

    const navControlsContent = renderNavControlComponent(templateOptions);
    const navControlsPath = path.join(deckRoot, NAV_CONTROLS_FILENAME);
    await fs.writeFile(navControlsPath, navControlsContent, 'utf8');

    return {
        navControlsPath,
    };
}

export async function cleanDevSwitcherFiles(deckRoot: string): Promise<void> {
    const navControlsPath = path.join(deckRoot, NAV_CONTROLS_FILENAME);
    await removeGeneratedIfOwned(navControlsPath);
}

async function removeGeneratedIfOwned(filePath: string): Promise<void> {
    const currentContent = await readFileIfExists(filePath);
    if (currentContent?.includes(GENERATED_MARKER)) {
        await fs.rm(filePath, { force: true });
    }
}

async function readFileIfExists(filePath: string): Promise<string | null> {
    try {
        return await fs.readFile(filePath, 'utf8');
    } catch (error: unknown) {
        if (isErrorWithCode(error, 'ENOENT')) {
            return null;
        }

        throw error;
    }
}

function isErrorWithCode(error: unknown, code: string): error is NodeJS.ErrnoException {
    return typeof error === 'object' && error !== null && 'code' in error && error.code === code;
}
