export interface DeckEntry {
    folder: string;
    label: string;
    slug: string;
    title?: string;
    detail?: string;
}

export interface SwitcherTemplateOptions {
    decks: DeckEntry[];
    currentSlug: string;
    bridgeUrl: string;
}

const SWITCH_TARGET_FRAME = 'slidev-manager-switch-target';

/** Generates `custom-nav-controls.vue` — compact dropdown for deck switching via form POST. Dev-only. */
export function renderNavControlComponent(options: SwitcherTemplateOptions): string {
    const { decks, currentSlug, bridgeUrl } = options;

    if (decks.length <= 1) {
        return `<template />\n`;
    }

    const bridgeAction = toBridgeActionPath(bridgeUrl);

    const menuItems = decks
        .map((deck) => {
            const isCurrent = deck.slug === currentSlug;
            const disabledAttr = isCurrent ? ' disabled' : '';
            const classAttr = isCurrent
                ? ' class="smgr-item smgr-item--active"'
                : ' class="smgr-item"';
            const formAction = `${bridgeAction}?folder=${encodeURIComponent(deck.folder)}`;
            const title = deck.title ?? deck.label;
            const detail = deck.detail ?? '';
            const detailMarkup = detail
                ? `\n            <span class="smgr-item-detail">${escapeHtml(detail)}</span>`
                : '';
            return `          <button type="submit" formaction="${escapeAttr(formAction)}"${classAttr}${disabledAttr}>\n            <span class="smgr-item-title">${escapeHtml(title)}</span>${detailMarkup}\n          </button>`;
        })
        .join('\n');

    return `<!-- Generated by vite-plugin-slidev-manager -->
<template>
  <div class="smgr-root">
    <details class="smgr-details">
      <summary class="smgr-trigger" title="Switch deck">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <rect x="3" y="4" width="18" height="13" rx="2" />
          <path d="M8 20h8" />
          <path d="M12 17v3" />
        </svg>
      </summary>
      <div class="smgr-menu-shell">
        <form method="POST" target="${SWITCH_TARGET_FRAME}" class="smgr-menu">
${menuItems}
        </form>
      </div>
    </details>
    <iframe
      name="${SWITCH_TARGET_FRAME}"
      class="smgr-target-frame"
      tabindex="-1"
      aria-hidden="true"
    />
  </div>
</template>

<style scoped>
.smgr-root {
  position: relative;
  display: inline-flex;
  --smgr-surface: #ffffff;
  --smgr-surface-hover: #f6f7f9;
  --smgr-surface-active: #eef4ff;
  --smgr-text: #111111;
  --smgr-muted: #666666;
  --smgr-border: #d8d8d8;
  --smgr-border-active: #bfd3ff;
  --smgr-shadow: 0 12px 32px rgba(15, 23, 42, 0.14);
}

.smgr-target-frame {
  display: none;
  width: 0;
  height: 0;
  border: 0;
}

.smgr-details {
  position: relative;
  display: flex;
  align-items: center;
}

.smgr-trigger {
  list-style: none;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 40px;
  height: 40px;
  padding: 0.5rem;
  border: 1px solid var(--smgr-border);
  border-radius: 999px;
  background: var(--smgr-surface);
  color: var(--smgr-text);
  cursor: pointer;
  transition: background-color 0.18s ease, border-color 0.18s ease, color 0.18s ease;
}

.smgr-trigger::-webkit-details-marker {
  display: none;
}

.smgr-trigger:hover {
  background: var(--smgr-surface-hover);
  border-color: color-mix(in srgb, var(--smgr-border) 76%, var(--slidev-theme-primary, #3b82f6));
}

.smgr-trigger:focus-visible {
  outline: 2px solid color-mix(in srgb, var(--slidev-theme-primary, #3b82f6) 30%, transparent);
  outline-offset: 2px;
}

.smgr-menu-shell {
  position: absolute;
  right: 0;
  bottom: calc(100% + 12px);
  display: none;
  width: min(24rem, calc(100vw - 2rem));
  max-height: min(24rem, calc(100vh - 4rem));
  overflow-y: auto;
  padding: 0.65rem;
  background: var(--smgr-surface);
  border: 1px solid var(--smgr-border);
  border-radius: 0.85rem;
  box-shadow: var(--smgr-shadow);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
  font-size: 12px;
  line-height: 1.4;
  z-index: 9999;
  color: var(--smgr-text);
}

.smgr-details[open] .smgr-menu-shell {
  display: block;
}

.smgr-menu {
  display: flex;
  flex-direction: column;
  gap: 0.3rem;
}

.smgr-item {
  all: unset;
  display: block;
  box-sizing: border-box;
  padding: 0.68rem 0.75rem;
  border: 1px solid transparent;
  border-radius: 0.7rem;
  background: transparent;
  color: inherit;
  cursor: pointer;
  text-align: left;
  transition: background-color 0.18s ease, border-color 0.18s ease;
}

.smgr-item-title {
  display: block;
  font-size: 0.84rem;
  font-weight: 600;
  line-height: 1.35;
}

.smgr-item-detail {
  display: block;
  margin-top: 0.18rem;
  color: var(--smgr-muted);
  font-size: 0.7rem;
  line-height: 1.4;
  white-space: normal;
  word-break: break-word;
}

.smgr-item:hover:not(:disabled) {
  background: var(--smgr-surface-hover);
  border-color: color-mix(in srgb, var(--smgr-border) 82%, var(--slidev-theme-primary, #3b82f6));
}

.smgr-item:focus-visible {
  outline: 2px solid color-mix(in srgb, var(--slidev-theme-primary, #3b82f6) 22%, transparent);
  outline-offset: 2px;
}

.smgr-item--active {
  background: var(--smgr-surface-active);
  border-color: var(--smgr-border-active);
}

.smgr-item--active .smgr-item-title {
  color: color-mix(in srgb, var(--smgr-text) 84%, var(--slidev-theme-primary, #3b82f6));
}

.smgr-item--active .smgr-item-detail {
  color: color-mix(in srgb, var(--smgr-text) 62%, var(--smgr-muted));
}

html.dark .smgr-root {
  --smgr-surface: #000000;
  --smgr-surface-hover: #111111;
  --smgr-surface-active: #0f172a;
  --smgr-text: #f5f5f5;
  --smgr-muted: #a3a3a3;
  --smgr-border: #2a2a2a;
  --smgr-border-active: #1d4ed8;
  --smgr-shadow: 0 18px 42px rgba(0, 0, 0, 0.45);
}
</style>
`;
}

function toBridgeActionPath(bridgeUrl: string): string {
    try {
        const url = new URL(bridgeUrl);
        const pathname = url.pathname.endsWith('/switch')
            ? url.pathname
            : `${url.pathname.replace(/\/+$/, '')}/switch`;
        return `${url.origin}${pathname}`;
    } catch {
        const normalized = bridgeUrl.replace(/\/+$/, '');
        return normalized.endsWith('/switch') ? normalized : `${normalized}/switch`;
    }
}

function escapeHtml(value: string): string {
    return value
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#39;');
}

function escapeAttr(value: string): string {
    return escapeHtml(value);
}
