import fs from 'node:fs/promises';
import path from 'node:path';
import type { DeckEntry } from './generated-switcher-template.js';
import {
    renderContextMenuSetup,
    renderNavControlComponent,
} from './generated-switcher-template.js';

export const SUPPORT_DIR_NAME = '.slidev-manager';
const MANIFEST_FILENAME = 'manifest.json';
const NAV_CONTROLS_FILENAME = 'custom-nav-controls.vue';
const CONTEXT_MENU_FILENAME = 'context-menu.ts';
const LEGACY_GLOBAL_TOP_FILENAME = 'global-top.vue';
const LEGACY_SWITCHER_COMPONENT_FILENAME = 'SwitcherOverlay.vue';
const SETUP_DIR_NAME = 'setup';
const NAV_CONTROLS_BACKUP_FILENAME = 'custom-nav-controls.original.vue';
const CONTEXT_MENU_BACKUP_FILENAME = 'context-menu.original.ts';
const GENERATED_MARKER = 'Generated by vite-plugin-slidev-manager';

export interface DevSwitcherManifest {
    generatedAt: string;
    currentSlug: string;
    bridgeUrl: string;
    decks: DeckEntry[];
}

export interface GenerateDevSwitcherOptions {
    deckRoot: string;
    decks: DeckEntry[];
    currentSlug: string;
    bridgeUrl: string;
    now?: Date;
}

export interface GenerateDevSwitcherResult {
    supportDir: string;
    navControlsPath: string;
    contextMenuPath: string;
    manifestPath: string;
    navControlsBackupPath: string;
    contextMenuBackupPath: string;
    manifest: DevSwitcherManifest;
}

export function buildSupportDirPath(deckRoot: string): string {
    return path.join(deckRoot, SUPPORT_DIR_NAME);
}

export async function generateDevSwitcherFiles(
    options: GenerateDevSwitcherOptions,
): Promise<GenerateDevSwitcherResult> {
    const { deckRoot, decks, currentSlug, bridgeUrl, now = new Date() } = options;

    const supportDir = buildSupportDirPath(deckRoot);
    await fs.mkdir(supportDir, { recursive: true });
    await removeLegacyGeneratedFiles(deckRoot, supportDir);

    const setupDir = path.join(deckRoot, SETUP_DIR_NAME);
    await fs.mkdir(setupDir, { recursive: true });

    const manifest: DevSwitcherManifest = {
        generatedAt: now.toISOString(),
        currentSlug,
        bridgeUrl,
        decks,
    };

    const manifestPath = path.join(supportDir, MANIFEST_FILENAME);
    await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

    const templateOptions = { decks, currentSlug, bridgeUrl };

    const navControlsContent = renderNavControlComponent(templateOptions);
    const navControlsPath = path.join(deckRoot, NAV_CONTROLS_FILENAME);
    const navControlsBackupPath = path.join(supportDir, NAV_CONTROLS_BACKUP_FILENAME);
    await backupIfUserOwned(navControlsPath, navControlsBackupPath);
    await fs.writeFile(navControlsPath, navControlsContent, 'utf8');

    const contextMenuContent = renderContextMenuSetup(templateOptions);
    const contextMenuPath = path.join(setupDir, CONTEXT_MENU_FILENAME);
    const contextMenuBackupPath = path.join(supportDir, CONTEXT_MENU_BACKUP_FILENAME);
    await backupIfUserOwned(contextMenuPath, contextMenuBackupPath);
    await fs.writeFile(contextMenuPath, contextMenuContent, 'utf8');

    return {
        supportDir,
        navControlsPath,
        contextMenuPath,
        manifestPath,
        navControlsBackupPath,
        contextMenuBackupPath,
        manifest,
    };
}

export async function cleanDevSwitcherFiles(deckRoot: string): Promise<void> {
    const supportDir = buildSupportDirPath(deckRoot);
    const setupDir = path.join(deckRoot, SETUP_DIR_NAME);
    await removeLegacyGeneratedFiles(deckRoot, supportDir);

    const navControlsPath = path.join(deckRoot, NAV_CONTROLS_FILENAME);
    const navControlsBackupPath = path.join(supportDir, NAV_CONTROLS_BACKUP_FILENAME);
    await restoreOrRemoveGenerated(navControlsPath, navControlsBackupPath);

    const contextMenuPath = path.join(setupDir, CONTEXT_MENU_FILENAME);
    const contextMenuBackupPath = path.join(supportDir, CONTEXT_MENU_BACKUP_FILENAME);
    await restoreOrRemoveGenerated(contextMenuPath, contextMenuBackupPath);

    await removeEmptyDir(setupDir);
    await fs.rm(supportDir, { recursive: true, force: true });
}

async function removeLegacyGeneratedFiles(deckRoot: string, supportDir: string): Promise<void> {
    const legacyGlobalTopPath = path.join(deckRoot, LEGACY_GLOBAL_TOP_FILENAME);
    const legacySwitcherPath = path.join(supportDir, LEGACY_SWITCHER_COMPONENT_FILENAME);

    await removeGeneratedIfOwned(legacyGlobalTopPath);
    await removeGeneratedIfOwned(legacySwitcherPath);
}

async function backupIfUserOwned(filePath: string, backupPath: string): Promise<void> {
    const existing = await readFileIfExists(filePath);
    if (existing && !existing.includes(GENERATED_MARKER)) {
        await fs.writeFile(backupPath, existing, 'utf8');
    }
}

async function restoreOrRemoveGenerated(filePath: string, backupPath: string): Promise<void> {
    const backupContent = await readFileIfExists(backupPath);
    if (backupContent !== null) {
        await fs.writeFile(filePath, backupContent, 'utf8');
        return;
    }

    const currentContent = await readFileIfExists(filePath);
    if (currentContent?.includes(GENERATED_MARKER)) {
        await fs.rm(filePath, { force: true });
    }
}

async function removeGeneratedIfOwned(filePath: string): Promise<void> {
    const currentContent = await readFileIfExists(filePath);
    if (currentContent?.includes(GENERATED_MARKER)) {
        await fs.rm(filePath, { force: true });
    }
}

async function removeEmptyDir(dirPath: string): Promise<void> {
    try {
        const entries = await fs.readdir(dirPath);
        if (entries.length === 0) {
            await fs.rmdir(dirPath);
        }
    } catch (error: unknown) {
        if (isErrorWithCode(error, 'ENOENT')) {
            return;
        }
        throw error;
    }
}

async function readFileIfExists(filePath: string): Promise<string | null> {
    try {
        return await fs.readFile(filePath, 'utf8');
    } catch (error: unknown) {
        if (isErrorWithCode(error, 'ENOENT')) {
            return null;
        }

        throw error;
    }
}

function isErrorWithCode(error: unknown, code: string): error is NodeJS.ErrnoException {
    return typeof error === 'object' && error !== null && 'code' in error && error.code === code;
}
