export interface DeckEntry {
    folder: string;
    label: string;
    slug: string;
    title?: string;
    detail?: string;
}

export interface SwitcherTemplateOptions {
    decks: DeckEntry[];
    currentSlug: string;
    bridgeUrl: string;
}

const SWITCH_TARGET_FRAME = 'slidev-manager-switch-target';

/** Generates `custom-nav-controls.vue` — compact dropdown for deck switching via form POST. Dev-only. */
export function renderNavControlComponent(options: SwitcherTemplateOptions): string {
    const { decks, currentSlug, bridgeUrl } = options;

    if (decks.length <= 1) {
        return `<template />\n`;
    }

    const menuItems = decks
        .map((deck) => {
            const isCurrent = deck.slug === currentSlug;
            const disabledAttr = isCurrent ? ' disabled' : '';
            const classAttr = isCurrent
                ? ' class="smgr-item smgr-item--active"'
                : ' class="smgr-item"';
            const formAction = `${bridgeUrl}?folder=${encodeURIComponent(deck.folder)}`;
            const title = deck.title ?? deck.label;
            const detail = deck.detail ?? '';
            const detailMarkup = detail
                ? `\n            <span class="smgr-item-detail">${escapeHtml(detail)}</span>`
                : '';
            return `          <button type="submit" formaction="${escapeAttr(formAction)}"${classAttr}${disabledAttr}>\n            <span class="smgr-item-title">${escapeHtml(title)}</span>${detailMarkup}\n          </button>`;
        })
        .join('\n');

    return `<!-- Generated by vite-plugin-slidev-manager -->
<template>
  <div class="smgr-root">
    <details class="smgr-details">
      <summary class="smgr-trigger" title="Switch deck">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <rect x="2" y="3" width="20" height="14" rx="2" />
          <path d="M8 21h8" />
          <path d="M12 17v4" />
        </svg>
      </summary>
      <div class="smgr-menu-shell">
        <form method="POST" target="${SWITCH_TARGET_FRAME}" class="smgr-menu">
${menuItems}
        </form>
      </div>
    </details>
    <iframe
      name="${SWITCH_TARGET_FRAME}"
      class="smgr-target-frame"
      tabindex="-1"
      aria-hidden="true"
    />
  </div>
</template>

<style scoped>
.smgr-root {
  position: relative;
  display: inline-flex;
}

.smgr-target-frame {
  display: none;
  width: 0;
  height: 0;
  border: 0;
}

.smgr-details {
  position: relative;
  display: flex;
  align-items: center;
}

.smgr-details[open] .smgr-trigger {
  opacity: 1;
}

.smgr-trigger {
  list-style: none;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  box-sizing: border-box;
  width: 40px;
  height: 40px;
  padding: 0.5rem;
  border-radius: 4px;
  color: currentColor;
  cursor: pointer;
  opacity: 0.5;
  transition: opacity 0.15s;
}

.smgr-trigger::-webkit-details-marker {
  display: none;
}

.smgr-trigger:hover {
  opacity: 1;
}

.smgr-trigger:focus-visible {
  opacity: 1;
  outline: 2px solid var(--slidev-theme-primary, #3b82f6);
  outline-offset: -2px;
  border-radius: 6px;
}

.smgr-menu-shell {
  position: absolute;
  right: 0;
  bottom: calc(100% + 10px);
  display: none;
  min-width: 220px;
  max-height: 320px;
  overflow-y: auto;
  padding: 6px;
  background: var(--slidev-theme-background, var(--slidev-controls-background, rgba(255, 255, 255, 0.92)));
  border: 1px solid var(--slidev-theme-border, rgba(0, 0, 0, 0.08));
  border-radius: 10px;
  box-shadow:
    0 8px 24px rgba(0, 0, 0, 0.12),
    0 2px 6px rgba(0, 0, 0, 0.06),
    0 0 0 1px rgba(0, 0, 0, 0.04);
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
  font-size: 13px;
  line-height: 1.4;
  z-index: 9999;
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  color: var(--slidev-theme-text, CanvasText);
}

@media (prefers-color-scheme: dark) {
  .smgr-menu-shell {
    background: var(--slidev-theme-background, var(--slidev-controls-background, rgba(30, 30, 30, 0.92)));
    border-color: var(--slidev-theme-border, rgba(255, 255, 255, 0.1));
    box-shadow:
      0 8px 24px rgba(0, 0, 0, 0.4),
      0 2px 6px rgba(0, 0, 0, 0.2),
      0 0 0 1px rgba(255, 255, 255, 0.06);
  }
}

.smgr-details[open] .smgr-menu-shell {
  display: block;
}

.smgr-menu {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.smgr-item {
  all: unset;
  display: block;
  box-sizing: border-box;
  padding: 7px 12px;
  border-radius: 6px;
  color: inherit;
  cursor: pointer;
  text-align: left;
  white-space: nowrap;
  transition: background-color 0.15s ease, color 0.15s ease, opacity 0.15s ease;
  opacity: 0.85;
}

.smgr-item-title {
  display: block;
  font-size: 0.92rem;
  font-weight: 600;
  line-height: 1.35;
}

.smgr-item-detail {
  display: block;
  margin-top: 0.15rem;
  font-size: 0.76rem;
  line-height: 1.3;
  opacity: 0.72;
  white-space: normal;
  word-break: break-word;
}

.smgr-item:hover:not(:disabled) {
  background-color: rgba(0, 0, 0, 0.06);
  opacity: 1;
}

.smgr-item:active:not(:disabled) {
  background-color: rgba(0, 0, 0, 0.1);
}

.smgr-item:focus-visible {
  outline: 2px solid var(--slidev-theme-primary, #3b82f6);
  outline-offset: -2px;
}

@media (prefers-color-scheme: dark) {
  .smgr-item:hover:not(:disabled) {
    background-color: rgba(255, 255, 255, 0.08);
  }

  .smgr-item:active:not(:disabled) {
    background-color: rgba(255, 255, 255, 0.12);
  }
}

.smgr-item--active {
  background-color: var(--slidev-theme-primary-surface, rgba(59, 130, 246, 0.12));
  color: var(--slidev-theme-primary, #3b82f6);
  opacity: 1;
  cursor: default;
}

.smgr-item--active .smgr-item-detail {
  opacity: 0.82;
}

.smgr-item--active:hover {
  background-color: var(--slidev-theme-primary-surface, rgba(59, 130, 246, 0.12));
}
</style>
`;
}

/** Generates `setup/context-menu.ts` — adds deck-switch entries to Slidev's context menu. Dev-only. */
export function renderContextMenuSetup(options: SwitcherTemplateOptions): string {
    void options;

    return `// Generated by vite-plugin-slidev-manager
export default (items) => items;
`;
}

function escapeHtml(text: string): string {
    return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escapeAttr(text: string): string {
    return text
        .replace(/&/g, '&amp;')
        .replace(/"/g, '&quot;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}
